### model
model_name_or_path: Qwen/Qwen3-VL-4B-Thinking
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
do_predict: true
finetuning_type: lora
lora_rank: 32
lora_target: all

### dataset
dataset: nudity_train, mma_train # mllm_demo,identity,alpaca_en_demo  # video: mllm_video_demo
template: qwen3_vl
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen3vl-4b-thinking/lora/sft_nudity_mma_split
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null # /workspace/LLaMA-Factory/saves/qwen3vl-4b/lora/sft_nudity_mma/checkpoint-195

### eval
eval_dataset: nudity_eval, mma_eval
# val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
# compute_accuracy: true
predict_with_generate: true
